# creates GTFS files with first (attributes) line
def init_GTFS():
    f = open('gtfs/trips.txt', 'w+')
    f.write('route_id,service_id,trip_id,trip_headsign,shape_id')
    f.close()
    f = open('gtfs/agency.txt', 'w+')
    f.write('agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url')
    f.write('\nLPP,http://www.lpp.si,Europe/Ljubljana,en,+38615822460,'
            'http://www.lpp.si/en/public-transport/information-bus-arrivals')
    f.close()
    f = open('gtfs/frequencies.txt', 'w+')
    f.write('trip_id,start_time,end_time,headway_secs')
    f.close()
    f = open('gtfs/calendar.txt', 'w+')
    f.write('service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date')
    f.close()
    f = open('gtfs/routes.txt', 'w+')
    f.write('route_id,route_short_name,route_long_name,route_type')
    f.close()
    f = open('gtfs/stops.txt', 'w+')
    f.write('stop_id,stop_name,stop_lat,stop_lon')
    f.close()
    f = open('gtfs/stop_times.txt', 'w+')
    f.write('trip_id,arrival_time,departure_time,stop_id,stop_sequence')
    f.close()
